version: "3"
services: 
  server: 
    build: .
    working_dir: /app
    env_file:
      - .env
    volumes: 
      - ./src/:/app/src
      - ./node_modules:/app/node_modules
    depends_on:
      - mongo
    ports:
      - '8000:8000'
    command: 'npm run start:dev'
  web:
    build:
      context: ./client
    command: npm start
    volumes:
      - ./client/:/app
      - ./client/node_modules/:/app/node_modules
    depends_on:
      - server
    ports:
      - '3000:3000'
  mongo:
    container_name: eras-mongo 
    image: mongo
    ports:
      - '27017:27017'
